#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PIDFILE=/var/run/lumi.pid

start_service()
{
	procd_open_instance
	procd_set_param pidfile $PIDFILE
	procd_set_param command node --max-old-space-size=32 /opt/lumi/lumi.js
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	kill $(cat $PIDFILE)
	rm $PIDFILE
}
